/**
 * Generated by orval 🍺
 * Do not edit manually.
 * randomuser.me
 * Hand-authored OpenAPI description of the upstream randomuser.me endpoint
 * we consume. Used by `orval` to generate the typed HTTP client and Zod
 * schema for `HttpUsersRepository`.
 *
 * This spec is the only place the upstream response shape is documented.
 * Drift between this file and the real upstream is caught by running
 * `pnpm orval` and reading the diff in the generated output.
 *
 * OpenAPI spec version: 1.0
 */
import * as zod from 'zod';

/**
 * @summary Fetch a deterministic list of random users.
 */
export const getRandomUsersQueryResultsDefault = 100;
export const getRandomUsersQueryResultsMax = 5000;



export const GetRandomUsersQueryParams = zod.object({
  "results": zod.int().min(1).max(getRandomUsersQueryResultsMax).default(getRandomUsersQueryResultsDefault).describe('Number of user records to return. We always pass 100.')
})

export const GetRandomUsersResponse = zod.object({
  "results": zod.array(zod.object({
  "gender": zod.enum(['male', 'female']),
  "name": zod.object({
  "title": zod.enum(['Mr', 'Mademoiselle', 'Mrs', 'Ms', 'Miss', 'Madame']),
  "first": zod.string(),
  "last": zod.string()
}),
  "location": zod.object({
  "street": zod.object({
  "number": zod.int(),
  "name": zod.string()
}),
  "city": zod.string(),
  "state": zod.string(),
  "country": zod.string(),
  "postcode": zod.union([zod.int(),zod.string()]),
  "coordinates": zod.object({
  "latitude": zod.string(),
  "longitude": zod.string()
}),
  "timezone": zod.object({
  "offset": zod.string(),
  "description": zod.string()
})
}),
  "email": zod.email(),
  "login": zod.object({
  "uuid": zod.uuid(),
  "username": zod.string(),
  "password": zod.string(),
  "salt": zod.string(),
  "md5": zod.string(),
  "sha1": zod.string(),
  "sha256": zod.string()
}),
  "dob": zod.object({
  "date": zod.iso.datetime({"offset":true}),
  "age": zod.int()
}),
  "registered": zod.object({
  "date": zod.iso.datetime({"offset":true}),
  "age": zod.int()
}),
  "phone": zod.string(),
  "cell": zod.string(),
  "id": zod.object({
  "name": zod.string(),
  "value": zod.string().nullable()
}),
  "picture": zod.object({
  "large": zod.url(),
  "medium": zod.url(),
  "thumbnail": zod.url()
}),
  "nat": zod.string()
})),
  "info": zod.object({
  "seed": zod.string(),
  "results": zod.int(),
  "page": zod.int(),
  "version": zod.string()
})
})
