/**
 * Generated by orval 🍺
 * Do not edit manually.
 * randomuser.me
 * Hand-authored OpenAPI description of the upstream randomuser.me endpoint
 * we consume. Used by `orval` to generate the typed HTTP client and Zod
 * schema for `HttpUsersRepository`.
 *
 * This spec is the only place the upstream response shape is documented.
 * Drift between this file and the real upstream is caught by running
 * `pnpm orval` and reading the diff in the generated output.
 *
 * OpenAPI spec version: 1.0
 */
import type {
  GetRandomUsersParams,
  RandomUsersResponse
} from './schemas';


export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;

export type getRandomUsersResponse200 = {
  data: RandomUsersResponse
  status: 200
}

export type getRandomUsersResponseDefault = {
  data: RandomUsersResponse
  status: Exclude<HTTPStatusCodes, 200>
}

export type getRandomUsersResponseSuccess = (getRandomUsersResponse200) & {
  headers: Headers;
};
export type getRandomUsersResponseError = (getRandomUsersResponseDefault) & {
  headers: Headers;
};

export type getRandomUsersResponse = (getRandomUsersResponseSuccess | getRandomUsersResponseError)

export const getGetRandomUsersUrl = (params?: GetRandomUsersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://randomuser.me/api/?${stringifiedParams}` : `https://randomuser.me/api/`
}

/**
 * @summary Fetch a deterministic list of random users.
 */
export const getRandomUsers = async (params?: GetRandomUsersParams, options?: RequestInit): Promise<getRandomUsersResponse> => {

  const res = await fetch(getGetRandomUsersUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getRandomUsersResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getRandomUsersResponse
}



