/**
 * Generated by orval 🍺
 * Do not edit manually.
 * randomuser.me
 * Hand-authored OpenAPI description of the upstream randomuser.me endpoint
 * we consume. Used by `orval` to generate the typed HTTP client and Zod
 * schema for `HttpUsersRepository`.
 *
 * This spec is the only place the upstream response shape is documented.
 * Drift between this file and the real upstream is caught by running
 * `pnpm orval` and reading the diff in the generated output.
 *
 * OpenAPI spec version: 1.0
 */

export type GetRandomUsersParams = {
/**
 * Number of user records to return. We always pass 100.
 * @minimum 1
 * @maximum 5000
 */
results?: number;
};
