/**
 * Generated by orval 🍺
 * Do not edit manually.
 * randomuser.me
 * Hand-authored OpenAPI description of the upstream randomuser.me endpoint
 * we consume. Used by `orval` to generate the typed HTTP client and Zod
 * schema for `HttpUsersRepository`.
 *
 * This spec is the only place the upstream response shape is documented.
 * Drift between this file and the real upstream is caught by running
 * `pnpm orval` and reading the diff in the generated output.
 *
 * OpenAPI spec version: 1.0
 */
import type { Coordinates } from './coordinates.ts';
import type { Street } from './street.ts';
import type { Timezone } from './timezone.ts';

export interface Location {
  street: Street;
  city: string;
  state: string;
  country: string;
  postcode: number | string;
  coordinates: Coordinates;
  timezone: Timezone;
}
