/**
 * Generated by orval 🍺
 * Do not edit manually.
 * randomuser.me
 * Hand-authored OpenAPI description of the upstream randomuser.me endpoint
 * we consume. Used by `orval` to generate the typed HTTP client and Zod
 * schema for `HttpUsersRepository`.
 *
 * This spec is the only place the upstream response shape is documented.
 * Drift between this file and the real upstream is caught by running
 * `pnpm orval` and reading the diff in the generated output.
 *
 * OpenAPI spec version: 1.0
 */
import type { DateOfBirth } from './dateOfBirth.ts';
import type { Id } from './id.ts';
import type { Location } from './location.ts';
import type { Login } from './login.ts';
import type { Name } from './name.ts';
import type { Picture } from './picture.ts';
import type { UserGender } from './userGender.ts';

export interface User {
  gender: UserGender;
  name: Name;
  location: Location;
  email: string;
  login: Login;
  dob: DateOfBirth;
  registered: DateOfBirth;
  phone: string;
  cell: string;
  id: Id;
  picture: Picture;
  nat: string;
}
